-- =============================================================================
-- MIGRATION 004: GUEST LEADS TABLE
-- Frontend'den form doldurulduğunda "Ödeme Adımına Geç" butonuna basılınca
-- misafir iletişim bilgilerini yakalamak için kullanılır.
-- RLS: Anon kullanıcılar sadece INSERT yapabilir (okuyamaz).
-- =============================================================================
-- Supabase SQL Editor'da çalıştırın:
-- https://supabase.com/dashboard/project/yghiynqrtstvchtcaeml/sql/new
-- =============================================================================

CREATE TABLE IF NOT EXISTS guest_leads (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT NOW(),

  -- Birincil Misafir Bilgileri
  guest_name          TEXT NOT NULL,
  guest_email         TEXT NOT NULL,
  guest_phone         TEXT NOT NULL,
  phone_country_code  TEXT,           -- Örn: '+90'
  phone_country_iso   TEXT,           -- Örn: 'TR'
  special_notes       TEXT,

  -- Konaklama Bilgileri
  check_in            DATE,
  check_out           DATE,
  nights              INTEGER,
  guest_count         INTEGER,
  currency            TEXT DEFAULT 'TRY',

  -- Sepet & Oda Detayları (JSON)
  cart_items          JSONB,          -- [{roomId, roomName, boardChoice, quantity, pricePerNight, totalPrice}]
  room_guests         JSONB,          -- [{roomLabel, guestName, guestNote}]

  -- Fiyat Özeti
  subtotal_price      NUMERIC(10,2),
  tax_amount          NUMERIC(10,2),
  final_total_price   NUMERIC(10,2),

  -- Durum Takibi
  status              TEXT DEFAULT 'PENDING',
  reservation_code    TEXT,
  source              TEXT DEFAULT 'web'
);

ALTER TABLE guest_leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_insert_guest_leads"
  ON guest_leads FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "service_role_all_guest_leads"
  ON guest_leads FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_guest_leads_email   ON guest_leads(guest_email);
CREATE INDEX IF NOT EXISTS idx_guest_leads_status  ON guest_leads(status);
CREATE INDEX IF NOT EXISTS idx_guest_leads_created ON guest_leads(created_at DESC);
